MISSING_REMITTANCE = "MISSING_REMITTANCE"
CUSTOMER_LOOKUP_FAILURE = "CUSTOMER_LOOKUP_FAILURE"
INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND"
AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
PARTIAL_PAYMENT = "PARTIAL_PAYMENT"
MULTI_INVOICE = "MULTI_INVOICE"
POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
LOW_CONFIDENCE = "LOW_CONFIDENCE"

ALL_REASON_CODES = [
    MISSING_REMITTANCE,
    CUSTOMER_LOOKUP_FAILURE,
    INVOICE_NOT_FOUND,
    AMOUNT_MISMATCH,
    PARTIAL_PAYMENT,
    MULTI_INVOICE,
    POSSIBLE_DUPLICATE,
    LOW_CONFIDENCE,
]
